### ISSUE TITLE
'Playlist' object has no attribute 'parse_links'

### ISSUE THREAD

**Issue by hdallp** [modkhi/yt-playlist#5]
```
Traceback (most recent call last):
  File "C:\Users\Windows\Desktop\yt-playlist-master\yt-playlist-download.py", line 38, in <module>
    run(pl)
  File "C:\Users\Windows\Desktop\yt-playlist-master\yt-playlist-download.py", line 12, in run
    links = pl.parse_links()
AttributeError: 'Playlist' object has no attribute 'parse_links'
```

**Comment by haloflooder** [comment]
Replace line 12 from

```py
    links = pl.parse_links()
```
to
```py
    links = pl.video_urls
```

PyTube made some breaking changes to their API
